<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [18]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
A   = [[1,3,4],
           [2,5,7],
           [5,9,6]]
B   = [[1,0,0],
           [0,1,0],
           [0,0,1]]
def matrix_mul(A, B):
     
    
# result will be 3x4 
    result = [[sum(a * b for a, b in zip(A_row, B_col))for B_col in zip(*B)]for A_row in A] 
  
    for r in result: 
        print(r) 
    # write your code
    return(r)#multiplication_of_A_and_B)
    
matrix_mul(A, B)

[1, 3, 4]
[2, 5, 7]
[5, 9, 6]


[5, 9, 6]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [1]:
import random
from random import uniform
import collections
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#take input from user

input_string = input("Enter a list of numbers or elements separated by space: ")
A = input_string.split()
print("user list is ", A)

# using map() to perform conversion from input string to integer 
A = list(map(int, A)) 

# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    # using random.choice() to get a random number  
    #  random_num = random.choice(test_list) 
    # using random.uniform() to get a random float number 
    rand_idx = len(A)-1
    #random_num = random.uniform(A[0],A[rand_idx]) 
    random_num = random.choice(A) 
    
    return random_num #selected_random_number

def sampling_based_on_magnitued():
    number = []       #declaring empty list
    for i in range(1,100):
        number1 = [pick_a_number_from_list(A)] #converting int to list to use collection.counter,
                                                    #the list elements will be string by default
        #print (type(number1) )
        number = number + number1   # appending 2 list into a singular one
# Declaring counter outside for loop:

    counter = collections.Counter(number)
    #print(number)
    print(counter)
#a = [1,1,1,1,2,2,2,2,3,3,4,5,5]
#counter=collections.Counter(a)
#print(counter)
# Counter({1: 4, 2: 4, 3: 2, 5: 2, 4: 1})
#print(counter.values())
# [4, 4, 2, 1, 2]
#print(counter.keys())
# [1, 2, 3, 4, 5]
#print(counter.most_common(3))
# [(1, 4), (2, 4), (3, 2)]
sampling_based_on_magnitued()


Enter a list of numbers or elements separated by space: 4 5 6 9 8 7 4 1 2 3 6 5 4 8 7 9 
user list is  ['4', '5', '6', '9', '8', '7', '4', '1', '2', '3', '6', '5', '4', '8', '7', '9']
Counter({7: 18, 4: 18, 8: 16, 5: 16, 6: 14, 9: 6, 1: 5, 2: 3, 3: 3})


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [29]:
import re          # for regular expression
# write your python code here  
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program

String = input("Enter some numbers or elements ")
print("user input is ", String)
#string1 = ''   # declaring another string
#new_string =''

def replace_digits(String):
    # write your code
    # \D - Matches any non-decimal digit. Equivalent to [^0-9]
    pattern1 = '\D'
    replace1 = ''
    string1 = re.sub(pattern1, replace1, String)
    #print(string1)
     # \d - Matches any decimal digit. Equivalent to [0-9]
    pattern = '\d'
    replace = '#'
    new_string = re.sub(pattern, replace, string1) 
    #print(new_string)

    return(new_string) # modified string which is after replacing the # with digits

replace_digits(String)

Enter some numbers or elements #2a$#b%c%561#
user input is  #2a$#b%c%561#


'####'

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [5]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure

input_student_string = input("Enter the names of the students separated by space: ")
Students = list(input_student_string.split())

input_marks_string = input("\nEnter the marks of the coresponding students separated by space: ")
A = list(input_marks_string.split())

# using map() to perform conversion from input string to integer 
Marks = list(map(int, A)) 
#Creating a dictionary combining 2 lists
dict = {k:v for k,v in zip(Students, Marks)}
#print(dict)

#Using dict comprehension
dict_IQR={k:v for k,v in dict.items() if v>25 and v<75} 
#print(dict_IQR)


def display_dash_board(Students, Marks):
    
    # write code for computing top top 5 students
    #top_5_students = # compute this
    top_5_students = {k:v for k,v in sorted(dict.items(), key=lambda x: x[1],reverse=True) [:5]}
    
    #firstNpairs = {k: Diction[k] for k in list(Diction.keys())[:n]}
    #print(top_5_students)
       
    
    # write code for computing top least 5 students
    #least_5_students = # compute this
    least_5_students = {k:v for k,v in sorted(dict.items(), key=lambda x: x[1]) [:5]}  
    #print(least_5_students)
    
    # write code for computing top least 5 students
    #students_within_25_and_75 = # compute this
    students_within_25_and_75={k:v for k,v in sorted(dict_IQR.items(), key=lambda x: x[1])}
    #print(students_within_25_and_75)
    return top_5_students, least_5_students, students_within_25_and_75


(top_5_students, least_5_students, students_within_25_and_75) = display_dash_board(Students, Marks)
#print(# those values)
print("\nStudents who got top 5 ranks, in the descending order of marks: " + str(top_5_students))
print("\nStudents who got least 5 ranks, in the increasing order of marks: " + str(least_5_students))
print("\nStudents who got marks_within_25_and_75: " + str(students_within_25_and_75))
    

Enter the names of the students separated by space: s1 s2 s3 

Enter the marks of the coresponding students separated by space: 12 23 45

Students who got top 5 ranks, in the descending order of marks: {'s3': 45, 's2': 23, 's1': 12}

Students who got least 5 ranks, in the increasing order of marks: {'s1': 12, 's2': 23, 's3': 45}

Students who got marks_within_25_and_75: {'s3': 45}


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [6]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure

#input_points = input("Enter the list of points in tuples separated by space: ")
#S = list(input_points.split())
#P = input("Enter the co ordinate of the source point in tuples: ")

Data = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
Point = (3,-4)

Output_List = list( (item[0]*Point[0]+item[1]*Point[1]) / math.sqrt ((item[0]**2+item [1]**2) * (Point[0]**2+Point[1]**2)) for item in Data)
Cosine_distance = list( math.acos(value) for value in Output_List )

value_cosinedistant = {k:v for k,v in zip(Data,Cosine_distance)}
Sorted_value_cosinedistant = {k:v for k,v in sorted(value_cosinedistant.items(), key=lambda x: x[1]) [:5]}
closest_points_to_p = list((ls for ls in Sorted_value_cosinedistant.keys() ))

print(closest_points_to_p)

# here S is list of tuples and P is a tuple ot len=2
"""def closest_points_to_p(S, P):
    # write your code here
    Output_List = list( (item[0]*P[0]+item[1]*P[1]) / math.sqrt ((item[0]**2+item [1]**2) * (P[0]**2+P[1]**2)) for item in S)
    Cosine_distance = list( math.acos(value) for value in Output_List )

    value_cosinedistant = {k:v for k,v in zip(S,Cosine_distance)}
    Sorted_value_cosinedistant = {k:v for k,v in sorted(value_cosinedistant.items(), key=lambda x: x[1]) [:5]}
    closest_points_to_p = list((ls for ls in Sorted_value_cosinedistant.keys() ))

    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)

points = closest_points_to_p(S, P)
print(points) #print the returned values
"""

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


'def closest_points_to_p(S, P):\n    # write your code here\n    Output_List = list( (item[0]*P[0]+item[1]*P[1]) / math.sqrt ((item[0]**2+item [1]**2) * (P[0]**2+P[1]**2)) for item in S)\n    Cosine_distance = list( math.acos(value) for value in Output_List )\n\n    value_cosinedistant = {k:v for k,v in zip(S,Cosine_distance)}\n    Sorted_value_cosinedistant = {k:v for k,v in sorted(value_cosinedistant.items(), key=lambda x: x[1]) [:5]}\n    closest_points_to_p = list((ls for ls in Sorted_value_cosinedistant.keys() ))\n\n    return closest_points_to_p  # its list of tuples\n\nS= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]\nP= (3,-4)\n\npoints = closest_points_to_p(S, P)\nprint(points) #print the returned values\n'

<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [1]:
import math
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure

#Reference :https://doubleroot.in/lessons/straight-line/position-of-a-point-relative-to-a-line/,
#https://stackoverflow.com/questions/56948506/how-to-extract-coefficients-from-a-line-equation-in-python-without-using-numpy
def i_am_the_one(Red,Blue,Line):
    for i in Lines:
        z = re.findall(r'[\d\.\-\+]+', i) #extracting the coefficients from line Equation
        for r in Red:
            equation_red=r[0]*float(z[0])+r[1]*float(z[1])+float(z[2])  #replacing red points in the equation
        for b in Blue:
            equation_blue=b[0]*float(z[0])+b[1]*float(z[1])+float(z[2]) #replacing blue points in the equation
        if(equation_red >0.0 and equation_blue<0.0):
            print("YES")
        else:
            print('NO')
    # your code
    return #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

yes_or_no = i_am_the_one(Red, Blue, Lines)
#print() # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [2]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    first_index = 0
    last_index = 0
    first_number = 0
    last_number = 0
    value_to_be_replaced =0
    string1 = string.split(',')
    
    for i in range(0,(len(string1))):
        if string1[i] != '_':
            last_index = i
            last_number = int(string1[i])
            value_to_be_replaced=int ((first_number+last_number) / ((last_index - first_index)+1))
        
            for a in range(first_index,last_index+1):
                string1[a] = value_to_be_replaced
            first_index = last_index
            first_number = int(string1[last_index])
    
    
    string2 = string1[::-1]  #reversing the string
    
    first_index = 0
    last_index = 0
    first_number = 0
    last_number = 0
    for i in range(0,(len(string2))):
        if string2[i] != '_':
            last_index = i
            last_number = int(string2[i])
            value_to_be_replaced = int ((first_number+last_number) / ((last_index - first_index)+1))
        
            for a in range(first_index,last_index+1):
                string2[a] = value_to_be_replaced
            break                      #looping till first non '_' value, then break

    
    return string2[::-1]    #Reversing final string

strings=["_,_,_,24","40,_,_,_,60","80,_,_,_,_","_,_,30,_,_,_,50,_,_"]    ##List of input strings
for string in strings:
    smoothed_values= curve_smoothing(string)
    print(smoothed_values)


[6, 6, 6, 6]
[20, 20, 20, 20, 20]
[16, 16, 16, 16, 16]
[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [26]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#Ref: https://stackoverflow.com/questions/952914/how-to-make-a-flat-list-out-of-list-of-lists
#Ref: https://stackoverflow.com/questions/2600191/how-can-i-count-the-occurrences-of-a-list-item

from itertools import chain
#from functools import reduce
#from collections import Iterable  # or from collections.abc import Iterable
#import operator
#from iteration_utilities import deepflatten   ---error in binder Requires: Python >=3.5 
from collections import Counter #Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    #probability of P(F|S) = P(F intersection S) / P(S)   #Conditional Probability
    SampleSpace=int(len(A))
    Numeratorcount = 0                    #assigning variable value
    #%timeit list(itertools.chain.from_iterable(A))       --- not working
    #%timeit list(chain.from_iterable(A))                --fastest for large dataset
    #%timeit reduce(operator.concat, A) #slower than chain iterable
    #%timeit reduce(operator.iconcat, A, [])              #faster than concat
    B=list(chain.from_iterable(A))      #making a single list from list of lists
     
    for r in range(len(allinput)):
        for i in range(len(A)):
            if(allinput[r][0]== A[i][0] and allinput[r][1]==A[i][1]):
                Numeratorcount+=1       #taking the count of P(F intersection S)
        ConditionalProbability = (Numeratorcount/SampleSpace)/ (B.count(allinput[r][1])/SampleSpace)
        print('P(',allinput[r][0],'|',allinput[r][1],')=',ConditionalProbability)
        Numeratorcount = 0              #assigning count ='0' for next iteration
    return
#Input List:
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
allinput = [['F1','S1'],['F1','S2'],['F1','S3'],['F2','S1'],['F2','S2'],['F2','S3'],['F3','S1'],['F3','S2'],['F3','S3'],['F4','S1'],['F4','S2'],['F4','S3']
        ,['F5','S1'],['F5','S2'],['F5','S3']]
compute_conditional_probabilites(A)

P( F1 | S1 )= 0.25
P( F1 | S2 )= 0.33333333333333337
P( F1 | S3 )= 0.0
P( F2 | S1 )= 0.25
P( F2 | S2 )= 0.33333333333333337
P( F2 | S3 )= 0.33333333333333337
P( F3 | S1 )= 0.0
P( F3 | S2 )= 0.33333333333333337
P( F3 | S3 )= 0.33333333333333337
P( F4 | S1 )= 0.25
P( F4 | S2 )= 0.0
P( F4 | S3 )= 0.33333333333333337
P( F5 | S1 )= 0.25
P( F5 | S2 )= 0.0
P( F5 | S3 )= 0.0


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [45]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
#Ref: https://stackoverflow.com/questions/11938964/how-to-find-common-words-and-print-them-using-python-command
def string_features(S1, S2):
    s1_splitted=S1.split()
    s2_splitted=S2.split()
    
    #using set union and intersection
    No_of_common_words = set(s1_splitted).intersection(set(s2_splitted))
    #No_of_common_words = set(s1_splitted) & (set(s2_splitted))
    Words_only_in_S1 = set(s1_splitted).difference(set(s2_splitted))
    Words_only_in_S2 = set(s2_splitted) - set(s1_splitted)

    a =(len(No_of_common_words))
    b = (Words_only_in_S1)
    c = (Words_only_in_S2)
    
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(" a."+str(a),"\n b."+str(b),"\n c."+str(c))

 a.7 
 b.{'first', '5', 'F'} 
 c.{'second', 'S', '3'}


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [57]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

import math
# you can free to change all these codes/structure
def compute_log_loss(A):
    error = 0
    for i in range(len(A)):
        error += ((float(A[i][0]) * math.log10(A[i][1])) + ((1-float(A[i][0])) * (math.log10(1-A[i][1]))))
    error = (error/len(A))*(-1)
    return error

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

print(compute_log_loss(A))

0.42430993457031635
